version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    hostname: docker-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/etc/conf.d:/etc/mysql/conf.d:ro
    env_file: .env
    environment:
        TZ: Asia/Chongqing
    restart: always

  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - "80:80"
      - "81:81" #aojia-service
      - "82:82" #cms-service
      - "83:83" #simple-shop  composer
      - "84:84" #shop.docker
      - "443:443"
      - "8089:8089"
      - "8080:8080" # third proxy nginx cms 
      - "8081:8081" # third proxy nginx cms
    hostname: docker-nginx
    volumes:
      - ./nginx/etc/sites:/etc/nginx/sites
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./nginx/etc/includes:/etc/nginx/includes
      #- ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./www:/var/www
    links:
      - web
      # - phpmyadmin
      # - php-good-practice 
      # - ghost 
      # - beanstalkd-console
      # - gollum
    extra_hosts:
      - "cmsadmin-domain-local.liweijia.com:172.18.0.6"
      - "oms-api-staging.liweijia.com:182.92.69.56"
      - "admin-staging.liweijia.com:182.92.69.56"
    environment:
        TZ: Asia/Chongqing
    restart: always

  web:
    image: registry.cn-hangzhou.aliyuncs.com/cool2rong/aliyun-docker-web
    #build: ./web
    container_name: web
    links:
      - redis
      - mysql
      # - golang
      - mongodb
      # - beanstalkd
    ports:
      - "9009:9001" #supervisord
      - "9050:9050"
      - "9003:9003" #xdebug
      #- "8000:8000" #sales-php-ga fronend
      - "9501:9501"
      - "9502:9502"
      - "8000:8000"
    hostname: docker-web
    volumes: 
      # - ./web/cron:/etc/pam.d/cron
      # - ./web/crontab:/etc/crontab
      - ./web/log:/var/log
      - ./web/supervisor:/etc/supervisor/conf.d
      - ./www:/var/www
      - ./web/composer:/root/.composer
      #- ./ssh-outside:/root/.ssh #windows10与docker的问题
    extra_hosts:
      - "you-local.aojiahome.com:172.16.100.6"
      - "youservice-local.aojiahome.com:172.16.100.6"
      - "youadmin-local.aojiahome.com:172.16.100.6"
      - "youweb-local.aojiahome.com:172.16.100.6"
      - "you1-local.aojiahome.com:172.16.100.6"
      - "youservice1-local.aojiahome.com:172.16.100.6"
      - "youadmin1-local.aojiahome.com:172.16.100.6"
      - "youweb1-local.aojiahome.com:172.16.100.6"
      - "shop-local.andaren.com:172.16.100.6"
      - "shopservice-local.andaren.com:172.16.100.6"
      - "shopadmin-local.andaren.com:172.16.100.6"
      - "local.mutoulaile.com:172.16.100.6"
      - "api-local.mutoulaile.com:172.16.100.6"
      - "admin-local.mutoulaile.com:172.16.100.6"
      - "pay-local.liweijia.com:172.16.100.6"
      - "cmsservice-local.liweijia.com:172.16.100.6"
      - "cmsadmin-local.liweijia.com:172.16.100.6"
      - "ums-staging.aojiahome.com:182.92.69.56"
      - "ums-staging.mutoulaile.com:182.92.69.56"
      - "docker_host:172.16.100.6"
      - "sales-local.liweijia.com:172.16.100.6"
      - "shopweb-local.liweijia.com:172.16.100.6"
      - "shopadmin-local.liweijia.com:172.16.100.6"
      - "shopservice-local.liweijia.com:172.16.100.6"
      - "shop-local.liweijia.com:172.16.100.6"
      - "cmsadmin-domain-local.liweijia.com:172.16.100.6"
      - "oms-api-staging.liweijia.com:182.92.69.56"
      - "api-staging.liweijia.com:182.92.69.56"
      - "www-staging.liweijia.com:182.92.69.56"
      - "webadmin-local.liweijia.com:172.16.100.6"
      - "m-local.liweijia.com:172.16.100.6"
      - "www-local.liweijia.com:172.16.100.6"
      - "admin-staging.liweijia.com:182.92.69.56"
      - "www-local.andaren.com:172.16.100.6"
    environment:
        TZ: Asia/Chongqing
    restart: always

  redis:
    image: redis
    container_name: redis
    volumes:
        - ./redis/data:/data
    ports:
        - "6379:6379"
    hostname: docker-redis
    environment:
        TZ: Asia/Chongqing
    restart: always

  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=laradock-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1024m
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - web
    restart: always

  # golang:
  #   build: ./golang
  #   container_name: golang
  #   ports:
  #     # - "2379:2379" #etcd
  #     # - "8123:8123"
  #     # - "8124:8124"
  #     # - "8125:8125"
  #     # - "8130:8130"
  #     # - "8131:8131"
  #     - "8080:8080" #beego-project
  #   volumes:
  #     - ./www_go:/go
  #     - ./golang/log:/var/log
  #     - ./golang/supervisor:/etc/supervisor/conf.d
  #     # - ./ssh-outside:/root/.ssh
  #   hostname: docker-golang
  #   #env_file: .env
  #   environment:
  #       TZ: Asia/Chongqing
  #       #GOPATH: /var/www/go
  #   restart: always
    # networks:
    #   default:
    #     ipv4_address: 172.19.0.6

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data
    hostname: docker-mongodb
    environment:
      TZ: Asia/Chongqing
    restart: always
    # networks:
    #   default:
    #     ipv4_address: 172.19.0.7

  # ghost:
  #   image: ghost:0.11.10
  #   container_name: ghost
  #   volumes:
  #     - ./ghost:/var/lib/ghost
  #   ports:
  #     - "2369:2368"
  #   environment:
  #     - NODE_ENV=production
  #   restart: always
  #   networks:
  #     default:
  #       ipv4_address: 172.19.0.8

  # crawlers:
  #   build: ./www/crawlers
  #   container_name: crawlers
  #   volumes:
  #     - ./www/crawlers:/usr/src/app
  #   restart: always

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   env_file: .env
  #   links:
  #     - mysql:db
  #   restart: always

  # php-good-practice:
  #   image: dordoka/reveal
  #   container_name: php-good-practice
  #   volumes:
  #     - ./reveal/php-good-practice:/home/reveal/presos
  #   restart: always

  # beanstalkd:
  #   image: schickling/beanstalkd
  #   container_name: beanstalkd
  #   ports:
  #     - "11300:11300"
  #   restart: always

  # beanstalkd-console:
  #   image: schickling/beanstalkd-console
  #   container_name: beanstalkd-console
  #   links:
  #     - beanstalkd
  #   restart: always

  # shadowsocks:
  #   image: littleqz/shadowsocks-client
  #   container_name: shadowsocks
  #   ports:
  #     - "1088:1080"
  #   env_file: .env
  #   restart: always

  # gollum:
  #   build: ./gollum
  #   container_name: gollum
  #   volumes: 
  #     - ./gollum/wiki:/wiki
  #   restart: always

# networks:
#     default:
#         driver: bridge
#         driver_opts:
#             com.docker.network.enable_ipv6: "false"
#         ipam:
#             driver: default
#             config:
#             - subnet: 172.19.0.0/24
#               gateway: 172.19.0.1