version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/etc/conf.d:/etc/mysql/conf.d
    env_file: .env
    environment:
        TZ: Asia/Chongqing
    restart: always

  nginx:
    image: nginx:1.9.8
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/etc/sites:/etc/nginx/sites
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./nginx/etc/includes:/etc/nginx/includes
      - ./nginx/logs:/var/log/nginx
      - ./www:/var/www
    links:
      - web
      # - phpmyadmin
      # - php-good-practice 
      # - ghost 
      # - beanstalkd-console
      # - gollum
    environment:
        TZ: Asia/Chongqing
    restart: always

  web:
    #image: php:5.6-fpm
    build: ./web
    container_name: web
    links:
      - redis
      - mysql
      # - beanstalkd
    ports:
      - "9009:9001"
    volumes: 
      # - ./web/cron:/etc/pam.d/cron
      # - ./web/crontab:/etc/crontab
      - ./web/log:/var/log
      - ./web/supervisor:/etc/supervisor/conf.d
      - ./www:/var/www
      - ./web/composer:/root/.composer
    environment:
        TZ: Asia/Chongqing
    restart: always

  # crawlers:
  #   build: ./www/crawlers
  #   container_name: crawlers
  #   volumes:
  #     - ./www/crawlers:/usr/src/app
  #   restart: always

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   env_file: .env
  #   links:
  #     - mysql:db
  #   restart: always

  # ghost:
  #   image: ghost:0.11.3
  #   container_name: ghost
  #   volumes:
  #     - ./ghost:/var/lib/ghost
  #   ports:
  #     - "2369:2368"
  #   environment:
  #     - NODE_ENV=production
  #   restart: always

  # php-good-practice:
  #   image: dordoka/reveal
  #   container_name: php-good-practice
  #   volumes:
  #     - ./reveal/php-good-practice:/home/reveal/presos
  #   restart: always

  # beanstalkd:
  #   image: schickling/beanstalkd
  #   container_name: beanstalkd
  #   ports:
  #     - "11300:11300"
  #   restart: always

  # beanstalkd-console:
  #   image: schickling/beanstalkd-console
  #   container_name: beanstalkd-console
  #   links:
  #     - beanstalkd
  #   restart: always

  # shadowsocks:
  #   image: littleqz/shadowsocks-client
  #   container_name: shadowsocks
  #   ports:
  #     - "1088:1080"
  #   env_file: .env
  #   restart: always

  # gollum:
  #   build: ./gollum
  #   container_name: gollum
  #   volumes: 
  #     - ./gollum/wiki:/wiki
  #   restart: always

  redis:
    image: redis
    container_name: redis
    volumes:
        - ./redis/data:/data
    ports:
        - "6379:6379"
    environment:
        TZ: Asia/Chongqing
    restart: always

